name: CI-CD-pipe-docker2

on:
  push:
    branches:
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v1
        
      - name: Check the repo
        run : cd ./week7_final_result/SA_model_DEMO_AVG && ls -la
        
      - name: docker build
        run: cd ./week7_final_result/SA_model_DEMO_AVG && docker build -t my_app_docker2 . 
        
      - name: test1
        run: (sleep 5 & docker run -p 5000:5000 my_app_docker2:latest) 
             | if grep -q "68.89 %" ; then echo 'Test1 passed'; else exit 1; fi
        
        
        
      - name: test2
        run: docker run -d -p 5000:5000 my_app_docker2:latest 
             & (sleep 3 && curl http://localhost:5000/ | if grep -q "Введите" ; then echo 'Test2 passed'; else exit 1; fi)
