name: CI-CD-pipe-docker

on:
  push:
    branches:
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v1
        
      - name: Check the repo
        run : cd ./week7_final_result/SA_model_DEMO_AVG && ls -la
        
      - name: docker build
        run: cd ./week7_final_result && docker build -t my_app_docker . 
        
      - name: test
        run: docker run -p 5000:5000 my_app_docker:latest & (sleep 5 && curl http://127.0.0.1:5000/)
