name: CI-CD-pipe

on:
  push:
    branches:
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v1
        
      - name: Check the repo
        run : cd ./week7_final_result/SA_model_DEMO_AVG && ls -la
        
      - name: Create the env
        run : pip install flask scikit-learn
      
      - name: test1
        run : cd ./week7_final_result/SA_model_DEMO_AVG/
              && (python SA_demo_AVG_final.py & sleep 4) 
              | if grep -q "привет" ; then echo 'Test1 passed'; else exit 1; fi
              
      - name: test2
        run : curl http://127.0.0.1:5000/ 
              | if grep -q "Введите" ; then echo 'Test2 passed'; else exit 1; fi
        
        
        

