name: CI-CD-pipe

on:
  push:
    branches:
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v1
        
      - name: Check the repo
        run : cd ./week7_final_result/SA_model_DEMO_AVG && ls -la
        
      - name: Create the env
        run : pip install flask scikit-learn
      
      - name: test the app
        run : python ./week7_final_result/SA_model_DEMO_AVG/SA_demo_AVG_final.py
              & (sleep 5 && (curl http://127.0.0.1:5000/ 
              | if grep -q "Введите" ; then echo 'Test passed'; else exit 1; fi))
        
        
        

